#!/usr/bin/env zsh

# Title:         consize
# Description:   A Bash script for converting and resizing images
# Author:        Shinichi Okada <okada.shin@gmail.com>
# Date:          2023-02-09

set -eu
VERSION="0.7.1"
SCRIPT_NAME=$(basename "$0")

# Keep readlinkf function
readlinkf() {
    [ "${1:-}" ] || return 1
    max_symlinks=40
    CDPATH='' # to avoid changing to an unexpected directory

    target=$1
    [ -e "${target%/}" ] || target=${1%"${1##*[!/]}"} # trim trailing slashes
    [ -d "${target:-/}" ] && target="$target/"

    cd -P . 2>/dev/null || return 1
    while [ "$max_symlinks" -ge 0 ] && max_symlinks=$((max_symlinks - 1)); do
        if [ ! "$target" = "${target%/*}" ]; then
            case $target in
            /*) cd -P "${target%/*}/" 2>/dev/null || break ;;
            *) cd -P "./${target%/*}" 2>/dev/null || break ;;
            esac
            target=${target##*/}
        fi

        if [ ! -L "$target" ]; then
            target="${PWD%/}${target:+/}${target}"
            printf '%s\n' "${target:-/}"
            return 0
        fi
        link=$(ls -dl -- "$target" 2>/dev/null) || break
        target=${link#*" $target -> "}
    done
    return 1
}

self=$(readlinkf "$0")
script_dir=${self%/*}
# For Debian APT remove line 8 to the above line and use the following line to
# define the script_dir
# script_dir="/usr/share/consize"

# Import files
# shellcheck disable=SC1091
{
    . "${script_dir}/lib/getoptions.sh"
    . "${script_dir}/lib/main_definition.sh"
    . "${script_dir}/lib/utils.sh"
    . "${script_dir}/lib/img2webp_definition.sh"
    . "${script_dir}/lib/jpg2png_definition.sh"
    . "${script_dir}/lib/jpg2webp_definition.sh"
    . "${script_dir}/lib/optimize_jpg_definition.sh"
    . "${script_dir}/lib/optimize_png_definition.sh"
    . "${script_dir}/lib/optimize_svg_definition.sh"
    . "${script_dir}/lib/organize_files_definition.sh"
    . "${script_dir}/lib/png2jpg_definition.sh"
    . "${script_dir}/lib/png2webp_definition.sh"
    . "${script_dir}/lib/resize_definition.sh"
    . "${script_dir}/lib/svg2jpg_definition.sh"
    . "${script_dir}/lib/svg2png_definition.sh"
    . "${script_dir}/lib/webp2jpg_definition.sh"
    . "${script_dir}/lib/webp2png_definition.sh"
    # import only one of helpers file
    # . "${script_dir}/lib/shell_helpers.sh"
    # or
    . "${script_dir}/lib/bash_helpers.sh"
}

# Keep it. You need this for main parser.
eval "$(getoptions parser_definition parse "$0") exit 1"
parse "$@"
eval "set -- $REST"

# CHECK ENVIRONMENT
# If you need to check OS uncomment this
# if [ "$(uname)" = "Linux" ]; then
#     echo "Your OS is Linux."
# elif [ "$(uname)" = "Darwin" ]; then
#     echo "Your OS is mac."
# fi

# If you are using Bash, check Bash version
# check_bash 5

# Check dependencies of your script
# check_cmd convert # imagemagick
# check_cmd cwebp # webp 
# check_cmd dwebp # webp
# check_cmd optipng # optipng
# check_cmd jpegoptim # jpegoptim
# check_cmd svgo # npm package npm install -g svgo
# check_cmd svgexport # npm package, npm install svgexport -g

# Add more commands.
# Don't forget to add your command in lib/main_definition.sh
if [ $# -gt 0 ]; then
    cmd=$1
    shift
    case $cmd in
    img2webp)
        eval "$(getoptions parser_definition_img2webp parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/img2webp.sh"
        fn_img2webp "$@"
        ;;
    jpg2png)
        eval "$(getoptions parser_definition_jpg2png parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/jpg2png.sh"
        fn_jpg2png "$@"
        ;;
    jpg2webp)
        eval "$(getoptions parser_definition_jpg2webp parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/jpg2webp.sh"
        fn_jpg2webp "$@"
        ;;
    optimize_jpg)
        eval "$(getoptions parser_definition_optimize_jpg parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/optimize_jpg.sh"
        fn_optimize_jpg "$@"
        ;;
    optimize_png)
        eval "$(getoptions parser_definition_optimize_png parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/optimize_png.sh"
        fn_optimize_png "$@"
        ;;
    optimize_svg)
        eval "$(getoptions parser_definition_optimize_svg parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/optimize_svg.sh"
        fn_optimize_svg "$@"
        ;;
    organize_files)
        eval "$(getoptions parser_definition_organize_files parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/organize_files.sh"
        fn_organize_files "$@"
        ;;
    png2jpg)
        eval "$(getoptions parser_definition_png2jpg parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/png2jpg.sh"
        fn_png2jpg "$@"
        ;;
    png2webp)
        eval "$(getoptions parser_definition_png2webp parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/png2webp.sh"
        fn_png2webp "$@"
        ;;
    resize)
        eval "$(getoptions parser_definition_resize parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/resize.sh"
        fn_resize
        ;;
    svg2jpg)
        eval "$(getoptions parser_definition_svg2jpg parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/svg2jpg.sh"
        fn_svg2jpg
        ;;
    svg2png)
        eval "$(getoptions parser_definition_svg2png parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/svg2png.sh"
        fn_svg2png
        ;;
    webp2jpg)
        eval "$(getoptions parser_definition_webp2jpg parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/webp2jpg.sh"
        fn_webp2jpg
        ;;
    webp2png)
        eval "$(getoptions parser_definition_webp2png parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/webp2png.sh"
        fn_webp2png
        ;;
    --) ;; # no subcommand, arguments only
    esac
fi
